proxies:
- name: 0.27|DE447 5401Mb
  server: 136.243.191.85
  type: ssr
  country: DE
  port: 443
  password: sEscPBiAD9K$&@79
  cipher: aes-128-ctr
  protocol: auth_aes128_md5
  obfs: tls1.2_ticket_auth
